use_frameworks!

platform :ios, '13.0'

target 'ZHHLiveAnimatingView_Example' do
  pod 'ZHHLiveAnimatingView', :path => '../'

  target 'ZHHLiveAnimatingView_Tests' do
    inherit! :search_paths

    
  end
end
